# Generated by Django 3.2.5 on 2021-07-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='models',
            new_name='model',
        ),
    ]
