# Generated by Django 3.2.3 on 2021-06-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='pet',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
    ]
